# this file is about the PHP server class

class Rphp::Server
	require 'fileutils'
	require 'listen'
	require 'tilt'

	attr_accessor :port, :input, :output

	def initialize(port = 4321)
		@port = port
		@input = 'ruby'
		@output = 'public_html'
	end

	def generate_initial_files
		Dir.mkdir @input unless Dir.exist?(@input)
		File.write(
			"#{@input}/index.php.erb", 
			"<h1>Generated by RPHP</h1>"
			) unless File.exist?("#{@input}/index.php.erb")
	end

	def parse_file filename
		generate_initial_files
		output = filename.split('.')[0]
		extension = filename.split('.')[1]
		engine = filename.split('.')[2]
		input_name = "#{output}.#{engine}"
		output_name = "#{output}.#{extension}"

		file = Tilt.new("ruby/#{filename}").render
		File.write("#{output}.#{extension}",file)
	end

	def start
		puts "PHP development server started at port #{@port}"
		`nohup php -S localhost:#{@port} -t #{@output} >/dev/null 2>&1 &`
		listen
	end

	def listen
		parse_file 'index.php.erb'
		listener = Listen.to(@input) do |modified, added, removed|
			parse_file 'index.php.erb'
		end
		listener.start # not blocking
		sleep
	end
end